### ISSUE TITLE
Contradictory license information

### ISSUE THREAD

**Issue by freemin7** [mforets/carlin#5]
The label in readme says MIT but the side bar says GLP-3.0

**Comment by mforets** [comment]
The licence is https://github.com/mforets/carlin/blob/master/LICENSE, GPL-3.0. I don't know why github displays the MIT in the icon, i can try to fix it later.

---

By the way, please note that I no longer maintain this repository. You may be interested to know that I recently added new methods for Carleman linearization in the project JuliaReach, more specifically  in https://github.com/JuliaReach/ReachabilityAnalysis.jl , see https://github.com/JuliaReach/ReachabilityAnalysis.jl/tree/master/src/Algorithms/CARLIN

If you have ideas to apply these methods I'm interested to discuss, drop me a message!

**Comment by freemin7** [comment]
Awesome, i was thinking about porting those methods to Julia! Great if they are already there.

**Comment by mforets** [comment]
i've updated the license badge in the README, using the service https://shields.io/category/license 

> Awesome, i was thinking about porting those methods to Julia! Great if they are already there.

not all methods are ported to Julia -- but the new Julia implementation is more powerful in some aspects, for example that i have successfully built matrices with millions of dimensions efficiently, because it does so by only operating with sparse matrices. the part that i didn't yet implement in Julia is the automatic translation from the polynomial ODE to the quadratic form `x' = F1 * x + F2 * (x \otimes x)`.

**Comment by freemin7** [comment]
If you ever want to implement this transform, please talk to @ChrisRackauckas and what benefits result from including it somewhere under the DiffEq eco system (probably modeling toolkit) since multiple things in the eco system could profit on the transform.
If you don't implement the transform in 2021, i might look into it or something.

**Comment by ChrisRackauckas** [comment]
I think doing a purely symbolic version via ModelingToolkit can allow for some extra optimizations when mixed with CSE and simplifications, but yes the numerical way is more flexible and powerful so both have certain advantages and disadvantages. 2021 will be an exciting time for these kinds of problems.

**Comment by mforets** [comment]
@freemin7  Sure I'll ping you if I have updates on that transform! (Don't hesitate to ping me if you want to discuss sth ;) )

@ChrisRackauckas Yes a fully symbolic approach or a combined symbolic/numeric approach would be very interesting. Then we need to take the matrix exponential of that beast / compute its action on vectors obtained by successive Kronecker powers. Maybe the symbolic arrays infrastructure that you are developing can help.

---

My renewed interest on this matter is related to applying (in the context of set propagation for nonlinear ODEs), the new error bounds from https://arxiv.org/pdf/2011.03185.pdf (see https://www.quantamagazine.org/new-quantum-algorithms-finally-crack-nonlinear-equations-20210105/ for a less technical introduction). Maybe the folks that are developing QC algorithms (https://julialang.org/blog/2019/12/yao-differentiable-quantum-programming/  ) become interested in this transform too.
